# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Goo-Canvas
version:      0.02
version_from: lib/Goo/Canvas.pm
installdirs:  site
requires:
    Cairo:                         1.00
    ExtUtils::Depends:             0.2
    ExtUtils::PkgConfig:           1.0
    Glib:                          1.103
    Gtk2:                          1.100

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
