--- #YAML:1.0
name:                Goo-Canvas
version:             0.06
abstract:            Perl interface to the GooCanvas
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cairo:                         1.00
    ExtUtils::Depends:             0.2
    ExtUtils::PkgConfig:           1.0
    Glib:                          1.103
    Gtk2:                          1.100
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
